spring:
  ai:
    openai:
      api-key: ${API_KEY}
      base-url: ${BASE_URL}
      chat:
        completions-path: ${COMPLETIONS_PATH}
        options:
          model: ${MODEL_ID}
          temperature: 0.8
          max-tokens: 2048
      embedding:
        embeddings-path: /embeddings
        options:
          model: embedding-3
    vectorstore:
      pgvector:
        initialize-schema: false
        dimensions: 2048
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/spring-ai-study

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG


