server:
  port: 8848
spring:
  ai:
    openai:
      api-key: ${ZHIPU_API_KEY}
      base-url: ${BASE_URL}
      chat:
        completions-path: ${COMPLETIONS_PATH}
        options:
          model: ${MODEL_ID}
          temperature: 0.8
          max-tokens: 2048

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
