server:
  port: 8853

spring:
  ai:
    openai:
      api-key: ${ZHIPU_API_KEY}
      base-url: ${BASE_URL}
      chat:
        completions-path: ${COMPLETIONS_PATH}
        options:
          model: ${MODEL_ID}
          temperature: 0.7
          max-tokens: 4096
      embedding:
        options:
          model: embedding-3
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 2048
        distance-type: COSINE_DISTANCE
        index-type: HNSW
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-ai-study
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.ai: DEBUG
